### ISSUE TITLE
Centring the buttons

### ISSUE THREAD

**Issue by VanshitaGandhi** [VanshitaGandhi/web-design-2-independent-project#1]
1) Having issue centring the _view my work_ and _contact buttons_
2) Also just wanted to know the best format for importing an illustrator file should be svg right?
@mackenzierose

**Comment by MacKenzieRose** [comment]
1. The easiest way to get an element to center is to make sure your CSS has a center style in it. For example, you could assign a `text-align: center` to your banner, which is the container for your button. (You'd need to re-align your text, though, because it would also be centered.) You could also actually add a grid or flexbox to your CSS too. Lots of different ways to approach it, depending on how you're looking to organize the rest of your site.

2. It depends on the content of the illustrator file, and how you're looking to use it. If you're working with something that needs be be scaled infinitely, then yes, you can export as an SVG (lesson here: https://learn-the-web.algonquindesign.ca/courses/web-design-2/exporting-from-illustrator/). But you might also find a PNG or other file type makes more sense? It really depends what it is, and what it's for.

**Comment by VanshitaGandhi** [comment]
Thanks @MacKenzieRose
